### ISSUE TITLE
Unable to locate package docker-ce-cli

### ISSUE THREAD

**Issue by mabouelk** [EBI-Metagenomics/emg-viral-pipeline#100]
Command: sudo apt-get install -y docker-ce-cli containerd.io

I got his 
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'

**Comment by hoelzer** [comment]
Hey @mabouelk , thanks for your interest in the pipeline.

Your problem is not directly related to the pipeline. Also, it is difficult to help without further information. On what kind of system do you try to install? On a local machine (laptop, workstation) or a cluster? Do you general have `sudo` permissions on the system?

If possible, follow this manual to install Docker:

https://docs.docker.com/engine/install/ubuntu/#install-docker-ce

(For Linux)
