### ISSUE TITLE
Error executing process > 'annotate:hmmscan_viphogs (1)'

### ISSUE THREAD

**Issue by christinepalermo** [EBI-Metagenomics/emg-viral-pipeline#125]
Virify fails to pull the hmmer singularity image:

ERROR ~ Error executing process > 'annotate:hmmscan_viphogs (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name quay.io-microbiome-informatics-hmmer-3.1b2.img.pulling.1715869876184 docker://quay.io/microbiome-informatics/hmmer:3.1b2 > /dev/null
  status : 255
  message:
    INFO:    Converting OCI blobs to SIF format
    FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: unable to create new build: while searching for mksquashfs
: exec: "mksquashfs": executable file not found in $PATH

 -- Check '.nextflow.log' file for details
[.nextflow.log](https://github.com/EBI-Metagenomics/emg-viral-pipeline/files/15338767/default.nextflow.log)

**Comment by mberacochea** [comment]
Hi @christinepalermo 

Apologies for a very delayed response. It seems that your `singularity` installation, it's missing mksquashfs. If you are running on an HPC cluster, you should contact your support team about this. Otherwise, you should try to re-install singularity or "squashfs-tools" which is the dependency that seems to be missing. 

Another approach would be to use docker, if you have that installed.

Cheers
