### ISSUE TITLE
error running the pipeline with Nextflow version 20.10

### ISSUE THREAD

**Issue by uludag** [EBI-Metagenomics/emg-viral-pipeline#50]
I get the following error when running the pipeline with Nextflow docker option

> Error executing process > 'preprocess:rename (1)'
> ...
> Command error:
>   Command 'ps' required by nextflow to collect task metrics cannot be found

I have checked that the relevant Docker image is missing the _ps_ command

> $ docker run --rm microbiomeinformatics/emg-viral-pipeline-python3:v1 ps
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "ps": executable file not found in $PATH: unknown.

--mahmut

**Comment by hoelzer** [comment]
@uludag thanks for reporting!

Ah, this happened when we switched from a set of different image sources to harmonize everything in [one place](https://hub.docker.com/search?q=microbiomeinformatics&type=image). 

@mberacochea the containers all need `ps` installed to function properly with the in-build runtime/resource collection in `nextflow`, e.g. something like:

```docker
RUN apt update && apt install -y procps wget gzip && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Can you take care of that? Or can I simply adjust the Dockerfiles and then they get autobuild and pushed to your team Dockerhub? 

@uludag Did you start the pipeline with `-with-timeline` or `-with-report`? And from the `master` branch? If you use the latest release tag `v0.2.0` it should work because other images are used, for example please try:

```bash
nextflow run EBI-Metagenomics/emg-viral-pipeline -r v0.2.0 --fasta "/home/$USER/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/nextflow/test/assembly.fasta" --cores 4 -profile local,docker
```

and adjust `-profile` according to your system.

**Comment by mberacochea** [comment]
I see, Nextflow needs a the following utilites installed to be able to collect the metrics:
```Make sure the following tools are available awk, date, grep, egrep, ps, sed, tail, tee in the system where the jobs are executed``` from: https://www.nextflow.io/docs/latest/tracing.html.

I will include them on the containers, I can provide an ETA but I will it as soon as I can.

**Comment by uludag** [comment]
@hoelzer  thanks for the example command-line, using the release tag `v0.2.0` I'm able to run the emg-viral workflow.

In my earlier attempts I was trying to run the workflow from a local folder obtained with _git-pull_ from the `master` branch. I did not try the `-with-timeline` or `-with-report` options.

**Comment by hoelzer** [comment]
@mberacochea yes exactly, thanks!

@uludag great. And yes, your run from the `master` branch explains the issue bc/ the moved Docker images don't have `ps` right now

**Comment by hoelzer** [comment]
@mberacochea I think this can be closed? Are the containers updated?

**Comment by mberacochea** [comment]
Hey, sorry I missed this one. They are not updated yet... I will try to get this done this week (I'm testing NF so my team needs this too).
