### ISSUE TITLE
Nextflow pull failure

### ISSUE THREAD

**Issue by neptuneyt** [EBI-Metagenomics/emg-viral-pipeline#51]
Dear developer,
Thanks for your such good jobs.
My problem is that I can not install ```emg-viral-pipeline``` by any method of your provided.
Nextflow method:
```
(PathoFact) [u@h@software]$ nextflow run EBI-Metagenomics/emg-viral-pipeline --fasta "/home/$USER/.nextflow/assets/EBI-Metagenomics/emg-viral-pipeline/nextflow/test/assembly.fasta" --cores 4 -profile local,docker -r v0.1
N E X T F L O W  ~  version 21.04.1
Launching `EBI-Metagenomics/emg-viral-pipeline` [maniac_saha] - revision: 5c1279c24b [v0.1]
WARN: DSL 2 PREVIEW MODE IS DEPRECATED - USE THE STABLE VERSION INSTEAD -- Read more at https://www.nextflow.io/docs/latest/dsl2.html#dsl2-migration-notes

Profile: local,docker

Current User: yut
Nextflow-version: 21.04.1
Starting time: 14-05-2021 15:20 UTC
Workdir location:
  /tmp/nextflow-work-yut
Databases location:
  nextflow-autodownload-databases

Dev ViPhOG database: v3
Dev Meta database: v2

Only run annotation: false

This workflow requires Nextflow version 20.01 or greater -- You are running version 21.04.1
```

**Comment by hoelzer** [comment]
@neptuneyt thanks for reporting and sorry this happens due to a version check we implemented for Nextflow and that thus not properly work since the version number was bumped from 20.x.x to 21.x.x. 

@mberacochea the code is here:
https://github.com/EBI-Metagenomics/emg-viral-pipeline/blob/master/virify.nf#L42

I think this code can be simply removed and replaced by

```
manifest {
    mainScript = 'virify.nf'
    nextflowVersion = '>=20.01.0'
}
```

in `nextflow.config` (https://github.com/EBI-Metagenomics/emg-viral-pipeline/blob/master/nextflow.config#L2)

**Comment by mberacochea** [comment]
Thank you @hoelzer I have a fix https://github.com/EBI-Metagenomics/emg-viral-pipeline/commit/20a8672ba8a5744f7f8d4a5db8d1d19c5907f25a I'm testing it.

@neptuneyt I'll merge the fix into dev and master as soon I finish testing it.

**Comment by mberacochea** [comment]
@neptuneyt can you try with `-r dev` (to use the dev branch)?
